<a href="https://colab.research.google.com/github/zhalehk/jupyterlab/blob/main/00_pytorch_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pytorch Fundementals

Resource notebook: https://www.learnpyTorch.io/00_pytorch_fundemetals

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [19]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### creating tensors



In [20]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [21]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
vector.ndim

1

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([7, 8])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
# TENSOR
TENSOR = torch.tensor([[1, 2, 3],
                       [3, 6, 9],
                      [2, 4, 5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [24]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [30]:
# Create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)